name: gradient_widgets_plus
description: A minimal set of Flutter widgets encased with beautiful gradients.
version: 1.0.0
homepage: https://github.com/chandrabezzo/Gradient-Widgets

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

